데스크탑 헤더 드롭다운 메뉴 추가
bgpworks/boxhero-landing-v2 pull request #91
Opened 2021-09-01 03:14 UTC by cho-hadam

- 데스크탑 헤더에 새로 생긴 메뉴 추가
- 드롭다운 메뉴로 변경   
components/desktop-header.jsx에 DropDownMenu, DropDownSubMenu 추가하였습니다.
- 드롭다운 메뉴 바깥쪽 클릭 시 메뉴 닫힘
hooks/useOutsideClick.js 추가하였습니다

아직 curMenu 관련 코드는 남아있습니다   
tr json 파일 키 정렬 전입니다 (사용 순서대로 배치되어 있습니다)

2021-09-01 05:59 UTC, jngbng requested changes

2021-09-01 05:59 UTC, jngbng commented on src/components/desktop-header.jsx
> +  const [isShow, setShow] = useState(false);
크게 상관은 없지만 `isShow` 랑 `setShow`랑 이름 깔맞춤이 안맞네요.
이전 코드 참고해서 이름을 `onChangeIsShow` 로 하죠.

2021-09-01 05:59 UTC, jngbng commented on src/components/desktop-header.jsx
> +  useOutsideClick(dropDownMenu, () => setShow(false));
`useClickOutside` 로 이름을 바꾸죠.

2021-09-01 05:59 UTC, jngbng commented on src/components/desktop-header.jsx
> +  const dropDownMenu = useRef();
`dropDownMenuRef` 나 `containerRef` 가 더 좋지 않을까요.

2021-09-01 05:59 UTC, jngbng commented on src/components/desktop-header.jsx
> +          alt="펼치기"
예전에도 안하긴 했지만, 이것도 다국어 적용해놓죠.

2021-09-01 05:59 UTC, jngbng commented on src/components/desktop-header.jsx
> +  children,
`children`이 마지막인게 좋지 않을까 하네요.

2021-09-01 05:59 UTC, jngbng commented on src/components/desktop-header.jsx
> +            curMenu={curMenu}
이건 이제 안쓰는 것 같은데요?

2021-09-01 05:59 UTC, jngbng commented on src/components/desktop-header.jsx
> +  subMenusClassName,
이거 꼭 subMenusClassName 이어야 하나요? top container class name을 받아서는 원하는 걸 못하나요?

2021-09-01 05:59 UTC, jngbng commented on src/components/desktop-header.module.css
> +  border: solid 1px #e0e0e3;
이거 색상 코드 참조.

2021-09-01 06:13 UTC, cho-hadam commented on src/components/desktop-header.jsx
> +            curMenu={curMenu}
이거는 관련 코드가 여기저기에 많아서 한꺼번에 삭제하려고 했습니다!

2021-09-01 08:41 UTC, jngbng commented on src/components/desktop-header.jsx
> +        <div className={styles.floatingMenuContianer}>
floatingMenuContainer 오타

2021-09-02 00:25 UTC, jngbng requested changes

2021-09-02 00:25 UTC, jngbng commented on src/components/desktop-header.jsx
> +            <Link to="/">
/usecase-sales

2021-09-02 00:25 UTC, jngbng commented on src/components/desktop-header.jsx
> +            <Link to="/">
/usecase-material

2021-09-02 00:25 UTC, jngbng commented on src/components/desktop-header.jsx
> +            <Link to="/">
/usecase-assets

2021-09-02 00:25 UTC, jngbng commented on src/components/desktop-header.jsx
> +                link="/"
삭제

2021-09-02 00:35 UTC, jngbng requested changes

2021-09-02 00:35 UTC, jngbng commented on src/components/desktop-header.jsx
> +                icon={svgSymbol}
isWhite 일 때는 svg가 흰색이어야 할 것 같군요.

2021-09-02 01:33 UTC, merged